### ISSUE TITLE
Which fonts should be set in preamble.tex ?

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [nathangrigg/vimhelppdf#13]
I tried Noto Sans, Liberation Serif and Courier fonts but he script would produce a pdf with wrong spacing..I tried Fira Code and it worked...

What other fonts besides Fira Code works ? 

Many Thanks

**Comment by nathangrigg** [comment]
What do you mean the wrong spacing? Could you maybe attach one page (or a screenshot) showing what happens?

**Comment by ReductoAdAbsurdum** [comment]
Good: Fira Code: https://ibb.co/tJb8G0W
Bad: Noto Sans: https://ibb.co/JdSPdvW

**Comment by nathangrigg** [comment]
Ah, thanks for the screenshot, that helps me understand what is happening here.

The vim help file uses spaces to align columns, so it will only look aligned if you use a monospace font (like Fira Code).  If you want something from the Noto family, try Noto Mono
